![New York City schoolbus](schoolbus.jpg)

Photo by [Jannis Lucas](https://unsplash.com/@jannis_lucas) on [Unsplash](https://unsplash.com).
<br>

Every year, American high school students take SATs, which are standardized tests intended to measure literacy, numeracy, and writing skills. There are three sections - reading, math, and writing, each with a **maximum score of 800 points**. These tests are extremely important for students and colleges, as they play a pivotal role in the admissions process.

Analyzing the performance of schools is important for a variety of stakeholders, including policy and education professionals, researchers, government, and even parents considering which school their children should attend. 

You have been provided with a dataset called `schools.csv`, which is previewed below.

You have been tasked with answering three key questions about New York City (NYC) public school SAT performance.

In [59]:
# Import libraries
import pandas as pd
import numpy as np

# Read in the data
schools = pd.read_csv("schools.csv")

# Preview the data
schools.head()

                                         school_name  ... percent_tested
0  New Explorations into Science, Technology and ...  ...            NaN
1                               Essex Street Academy  ...           78.9
2                       Lower Manhattan Arts Academy  ...           65.1
3    High School for Dual Language and Asian Studies  ...           95.9
4      Henry Street School for International Studies  ...           59.7

[5 rows x 7 columns]

### Question 1

In [60]:
best_math_schools=schools[schools['average_math']>640]
best_math_schools=best_math_schools[['school_name','average_math']].sort_values('average_math',ascending=False)

### Question 2

In [61]:
schools['total_SAT']=schools['average_math']+schools['average_reading']+schools['average_writing']
top_10_schools=schools[['school_name','total_SAT']].nlargest(10,'total_SAT')

### Question 3

In [62]:
agg_schools=schools.groupby('borough').agg(num_schools=('school_name','count'),average_SAT=('total_SAT',np.mean),std_SAT=('total_SAT',np.std)).round(2)
largest_std_dev=agg_schools.nlargest(1,'std_SAT')